using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
namespace MacroTracker {
public static class FeatureUiTests {
 static IEnumerable<DependencyObject> Walk(DependencyObject root){for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++){var c=VisualTreeHelper.GetChild(root,i);yield return c;foreach(var d in Walk(c))yield return d;}}
 static void Click(Window w,string text){Walk(w).OfType<Button>().First(b=>(string)b.Content==text).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));}
 static void Capture(Window w,string file){w.UpdateLayout();var v=(FrameworkElement)w.Content;var b=new RenderTargetBitmap((int)v.ActualWidth,(int)v.ActualHeight,96,96,PixelFormats.Pbgra32);b.Render(v);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(b));using(var f=File.Create(file))encoder.Save(f);}
 static void Modal(MainWindow main,string method,object[] args,Action<Window> test){Exception failure=null;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(250)};timer.Tick+=delegate{timer.Stop();var w=Application.Current.Windows.Cast<Window>().First(x=>x!=main);try{test(w);}catch(Exception e){failure=e;w.Close();}};timer.Start();typeof(MainWindow).GetMethod(method,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(main,args);if(failure!=null)throw failure;}
 static void OpenModal(MainWindow main,Action open,Action<Window> test){Exception failure=null;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(250)};timer.Tick+=delegate{timer.Stop();var w=Application.Current.Windows.Cast<Window>().First(x=>x!=main);try{test(w);}catch(Exception e){failure=e;}finally{w.Close();}};timer.Start();open();if(failure!=null)throw failure;}
 public static void Run(MainWindow main,Store s){var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(350)};timer.Tick+=delegate{timer.Stop();try{
 s.Set("setup","1");s.SaveFood(null,DateTime.Today,"Egg",new double[]{70,6,1,5},"Breakfast","1 egg","","08:00");
 var items=s.Foods(DateTime.Today).Select(LibraryItem.From).ToList();
 Modal(main,"LibraryEditor",new object[]{items,null},delegate(Window w){var fields=Walk(w).OfType<TextBox>().ToList();fields[0].Text="UI breakfast";fields[1].Text="2";fields[2].Text="100";Capture(w,s.Path+".recipe.png");Click(w,"Save to library");});
 var record=s.Db.Query("SELECT * FROM library WHERE name='UI breakfast'").Single();
 Modal(main,"LogSaved",new object[]{record},delegate(Window w){Click(w,"Add all ingredients");});
 if(s.Totals(DateTime.Today)[0]!=105)throw new Exception("UI recipe scaling failed");
 Modal(main,"ScanLabel",new object[0],delegate(Window w){if(!Walk(w).OfType<Button>().Any(b=>(string)b.Content=="Access camera"))throw new Exception("Nutrition label camera button missing");var fields=Walk(w).OfType<TextBox>().ToList();fields[0].Text="Serving size 1 cup\nCalories 200\nTotal Fat 5g\nTotal Carbohydrate 25g\nProtein 15g\nSodium 120mg";Click(w,"Extract from text");fields[1].Text="UI reviewed label";Walk(w).OfType<CheckBox>().Single().IsChecked=true;Capture(w,s.Path+".label.png");Click(w,"Save reviewed food to favorites");});
 if(s.Db.Query("SELECT * FROM favorites WHERE name='UI reviewed label'").Count!=1)throw new Exception("Label review save failed");
 main.Navigate("Day Targets");var targets=Walk(main).OfType<TextBox>().Where(x=>x.Name!="PART_TextBox").ToList();targets[0].Text="UI Rest";Click(main,"Save preset");if(s.Db.Query("SELECT * FROM presets WHERE name='UI Rest'").Count!=1)throw new Exception("Preset UI save failed");
 main.Navigate("Check-In");Click(main,"Save check-in · keep targets");if(s.Db.Query("SELECT * FROM checkins").Count!=1)throw new Exception("Check-in UI save failed");
 main.Navigate("Settings");var reminderPicker=Walk(main).OfType<ComboBox>().First(c=>c.Name=="ReminderPicker");if(reminderPicker.Items.Count!=s.Db.Query("SELECT * FROM reminders").Count)throw new Exception("Reminder dropdown is incomplete");if(Walk(main).OfType<Button>().Count(b=>Convert.ToString(b.Content)=="Save reminder")!=1)throw new Exception("Settings should show one reminder editor");string firstTime=Walk(main).OfType<TextBox>().First(t=>t.Name=="ReminderTime").Text;reminderPicker.SelectedIndex=1;main.Dispatcher.Invoke(new Action(delegate{}),DispatcherPriority.DataBind);if(Walk(main).OfType<TextBox>().First(t=>t.Name=="ReminderTime").Text==firstTime)throw new Exception("Reminder dropdown did not change the editor");reminderPicker.BringIntoView();main.Dispatcher.Invoke(new Action(delegate{}),DispatcherPriority.Render);Capture(main,s.Path+".reminders.png");
 main.Navigate("Dashboard");var datePicker=Walk(main).OfType<SoftDatePicker>().First();OpenModal(main,delegate{datePicker.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));},delegate(Window w){if(w.Name!="MacroCalendar"||!Walk(w).OfType<TextBlock>().Any(t=>t.Text=="Sun")||!Walk(w).OfType<Button>().Any(b=>Convert.ToString(b.Content)=="Today"))throw new Exception("Themed calendar is incomplete");Capture(w,s.Path+".calendar.png");});
 var navigation=(StackPanel)typeof(MainWindow).GetField("navigation",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(main);if(navigation.Orientation!=Orientation.Horizontal||navigation.Children.OfType<Button>().Count()!=8)throw new Exception("Top navigation is incomplete");var ring=Walk(main).OfType<Canvas>().First(c=>c.Name=="CombinedMacroRing");if(ring.Children.OfType<System.Windows.Shapes.Ellipse>().Count()!=1||ring.Children.OfType<System.Windows.Shapes.Polyline>().Count()!=3||Walk(main).OfType<ProgressBar>().Count(b=>b.Name.StartsWith("MacroBar"))!=3)throw new Exception("Combined macro ring and bars are incomplete");
 for(int i=1;i<=3;i++){var d=DateTime.Today.AddDays(-i);s.SaveFood(null,d,"Streak day",new double[]{500,40,40,15},"Dinner","1 meal","","18:00");s.MarkComplete(d,true);}main.Navigate("Dashboard");if(!Walk(main).OfType<TextBlock>().Any(t=>t.Name=="LoggingStreak"&&t.Text.Contains("3 day")))throw new Exception("Meal logging streak is incorrect");
 var chartStart=Store.Sunday(DateTime.Today).AddDays(-7);var chartValues=new[]{2000.0,2400.0,2700.0};for(int i=0;i<3;i++){var d=chartStart.AddDays(i);s.SaveFood(null,d,"Chart day",new[]{chartValues[i],50.0,50.0,20.0},"Dinner","1 day","","18:00");s.MarkComplete(d,true);}typeof(MainWindow).GetField("selected",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(main,chartStart);main.Navigate("Dashboard");main.UpdateLayout();main.Dispatcher.Invoke(new Action(delegate{}),DispatcherPriority.Render);var states=Walk(main).OfType<System.Windows.Shapes.Rectangle>().Select(x=>Convert.ToString(x.Tag)).ToList();foreach(var expected in new[]{"Under","Near","Over"})if(!states.Contains(expected))throw new Exception("Weekly chart is missing "+expected+" status");
 foreach(string theme in new[]{"Graphite","Purple","White / Red / Blue"}){main.Navigate("Settings");Walk(main).OfType<ComboBox>().First(c=>c.Items.Cast<object>().Contains("Graphite")).SelectedItem=theme;Click(main,"Apply theme");main.UpdateLayout();main.Dispatcher.Invoke(new Action(delegate{}),DispatcherPriority.ContextIdle);var settingsContent=(StackPanel)typeof(MainWindow).GetField("content",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(main);var plain=Walk(settingsContent).OfType<Button>().Where(b=>b.Background==null||b.Background.ToString()!=MainWindow.Green.ToString()).Select(b=>Convert.ToString(b.Content)).ToList();if(plain.Count>0)throw new Exception("Settings buttons without theme accent: "+string.Join(", ",plain));var picker=Walk(main).OfType<ComboBox>().First(c=>c.Items.Cast<object>().Contains("Graphite"));picker.ApplyTemplate();var toggle=Walk(picker).OfType<System.Windows.Controls.Primitives.ToggleButton>().First();toggle.SetCurrentValue(System.Windows.Controls.Primitives.ToggleButton.IsCheckedProperty,true);main.Dispatcher.Invoke(new Action(delegate{}),DispatcherPriority.DataBind);if(!picker.IsDropDownOpen)throw new Exception("Rounded dropdown toggle did not open");main.Dispatcher.Invoke(new Action(delegate{}),DispatcherPriority.Render);Capture(main,s.Path+"."+theme.Split(' ')[0]+"-settings.png");var option=(ComboBoxItem)picker.ItemContainerGenerator.ContainerFromIndex(1);if(option==null)throw new Exception("Dropdown items not generated");option.IsSelected=true;if((string)picker.SelectedItem!="Purple")throw new Exception("Dropdown selection failed");picker.IsDropDownOpen=false;main.Navigate("Dashboard");Capture(main,s.Path+"."+theme.Split(' ')[0]+".png");}
 File.WriteAllText(s.Path+".feature-ui-results.txt","PASS: top navigation, combined macro ring and bars, calorie status colors, logging streak, reminders, calendar, and three themes.");
 }catch(Exception e){File.WriteAllText(s.Path+".feature-ui-error.txt",e.ToString());}finally{main.Exit();}};timer.Start();}
}
}
