using System;
using System.Linq;
using System.Windows.Controls;
namespace MacroTracker {
public sealed partial class MainWindow {
 void SelectDiaryMeal(){StackPanel p;var w=Form("Save foods from diary",out p);var date=new SoftDatePicker(w,selected);p.Children.Add(date);var list=new ListBox{SelectionMode=SelectionMode.Multiple,Height=350,DisplayMemberPath="Value"};p.Children.Add(list);Action load=delegate{list.ItemsSource=store.Foods(date.SelectedDate??selected).Select(r=>new System.Collections.Generic.KeyValuePair<System.Collections.Generic.Dictionary<string,string>,string>(r,r["time"]+" · "+r["name"]+" · "+r["category"])).ToList();};date.SelectedDateChanged+=delegate{load();};load();p.Children.Add(Label("Select foods with Ctrl-click or Shift-click.",13,Muted));p.Children.Add(Button("Create saved meal / recipe",delegate{var items=list.SelectedItems.Cast<System.Collections.Generic.KeyValuePair<System.Collections.Generic.Dictionary<string,string>,string>>().Select(x=>LibraryItem.From(x.Key)).ToList();if(items.Count==0)throw new ArgumentException("Select at least one food.");w.Close();LibraryEditor(items);},true));w.ShowDialog();}
 void IngredientEditor(Action<LibraryItem> accept){StackPanel p;var w=Form("Add an ingredient",out p);var name=Field(p,"Ingredient name","");var serving=Field(p,"One serving","1 serving");var quantity=Field(p,"Quantity","1");var fields=new TextBox[4];for(int i=0;i<4;i++)fields[i]=Field(p,Store.MacroNames[i]+" per serving","");var category=Choose(p,"Category",Store.Categories,"Other");p.Children.Add(Button("Search USDA",delegate{SearchUsda(w,delegate(UsdaFood food,double basis,string definition,double count){name.Text=food.Name;serving.Text=definition;quantity.Text=FoodPortion.Precise(count);for(int i=0;i<4;i++)fields[i].Text=food.Macros[i].HasValue?FoodPortion.Precise(food.Macros[i].Value*basis/100/count):"";},name.Text);}));p.Children.Add(Button("Add ingredient",delegate{double q=ReadQuantity(quantity);var v=FoodPortion.Scale(fields.Select(f=>Number(f,false)).ToArray(),q);if(string.IsNullOrWhiteSpace(name.Text)||name.Text.Length>200||string.IsNullOrWhiteSpace(serving.Text))throw new ArgumentException("Enter a name and serving size.");accept(new LibraryItem{Name=name.Text,Serving=serving.Text,Quantity=q,Category=(string)category.SelectedItem,Notes="",Macros=v});w.Close();},true));w.ShowDialog();}
}
}
