using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media.Imaging;
using Microsoft.Win32;
namespace MacroTracker {
public static class LabelReader {
 static string Single(string text,string pattern){var matches=Regex.Matches(text,pattern,RegexOptions.IgnoreCase);return matches.Count==1?matches[0].Groups[1].Value:"";}
 static string NearbyCalories(string text){var lines=Regex.Split(text??"",@"\r?\n");var found=new List<string>();for(int i=0;i<lines.Length;i++){if(!Regex.IsMatch(lines[i],@"^\s*Calories\s*:?[\s]*$",RegexOptions.IgnoreCase))continue;for(int n=i+1;n<Math.Min(lines.Length,i+8);n++){var match=Regex.Match(lines[n],@"^\s*(\d{1,4})\s*(?:kcal)?\s*$",RegexOptions.IgnoreCase);if(match.Success){found.Add(match.Groups[1].Value);break;}}}return found.Distinct().Count()==1?found[0]:"";}
 static string ProteinWithoutUnit(string text,string calories){var matches=Regex.Matches(text??"",@"^\s*Protein\s*:?\s*([0-9OoIl]+(?:\.[0-9]+)?)\s*$",RegexOptions.IgnoreCase|RegexOptions.Multiline);if(matches.Count!=1)return "";string token=matches[0].Groups[1].Value.Replace('O','0').Replace('o','0').Replace('I','1').Replace('l','1');double value;if(!double.TryParse(token,NumberStyles.Float,CultureInfo.InvariantCulture,out value))return "";double serving=0,energy=0;var servingMatch=Regex.Match(text??"",@"Serving\s+size[^\r\n]*?(\d+(?:\.\d+)?)\s*g",RegexOptions.IgnoreCase);if(servingMatch.Success)double.TryParse(servingMatch.Groups[1].Value,NumberStyles.Float,CultureInfo.InvariantCulture,out serving);double.TryParse(calories,NumberStyles.Float,CultureInfo.InvariantCulture,out energy);bool impossible=(serving>0&&value>serving+.5)||(energy>0&&value*4>energy+5);if(impossible&&token.Length>1&&(token.EndsWith("0")||token.EndsWith("9"))){double corrected;if(double.TryParse(token.Substring(0,token.Length-1),NumberStyles.Float,CultureInfo.InvariantCulture,out corrected)&&corrected>=0&&(!servingMatch.Success||corrected<=serving+.5))value=corrected;else return "";}return FoodPortion.Precise(value);}
 public static string[] Parse(string text){var result=new string[4];result[0]=Single(text,@"Calories\s*:?\s*(\d+(?:\.\d+)?)(?![\d.])");if(result[0]==""&&!Regex.IsMatch(text??"",@"Calories\s*:?\s*\d",RegexOptions.IgnoreCase))result[0]=NearbyCalories(text);result[1]=Single(text,@"Protein\s*:?\s*(\d+(?:\.\d+)?)\s*g");if(result[1]=="")result[1]=ProteinWithoutUnit(text,result[0]);result[2]=Single(text,@"(?:Total\s+Carbohydrate|Carbohydrate|Carbs)\s*:?\s*(\d+(?:\.\d+)?)\s*g");result[3]=Single(text,@"Total\s+Fat\s*:?\s*(\d+(?:\.\d+)?)\s*g");return result;}
 public static string Read(string image){string folder=Path.Combine(Path.GetTempPath(),"MacroTracker-OCR-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);string script=Path.Combine(folder,"LabelOcr.ps1"),output=Path.Combine(folder,"text.txt");using(var input=Assembly.GetExecutingAssembly().GetManifestResourceStream("LabelOcr"))using(var file=File.Create(script))input.CopyTo(file);var start=new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),@"WindowsPowerShell\v1.0\powershell.exe"),"-NoProfile -NonInteractive -File "+UpdatePackage.Quote(script)+" -ImagePath "+UpdatePackage.Quote(image)+" -OutputPath "+UpdatePackage.Quote(output)){UseShellExecute=false,CreateNoWindow=true};using(var process=Process.Start(start)){if(!process.WaitForExit(45000)){process.Kill();throw new IOException("Label recognition timed out. Try a smaller, clearer image.");}if(process.ExitCode!=0||!File.Exists(output))throw new IOException("Windows could not read this image. Check that an OCR language is installed and scripts are permitted. You can paste label text instead. Details: "+folder);}return File.ReadAllText(output);}
}
public sealed partial class MainWindow {
 void ScanLabel(){StackPanel p;var w=Form("Scan and review a nutrition label",out p);w.Width=900;var layout=new Grid();layout.ColumnDefinitions.Add(new ColumnDefinition());layout.ColumnDefinitions.Add(new ColumnDefinition());var preview=new Image{Height=250,Stretch=System.Windows.Media.Stretch.Uniform};layout.Children.Add(preview);var right=new StackPanel{Margin=new Thickness(12)};Grid.SetColumn(right,1);layout.Children.Add(right);var text=Field(right,"Recognized label text (editable)","");text.AcceptsReturn=true;text.Height=210;p.Children.Add(layout);var message=Label("Select a clear English nutrition label or paste its image. Review values before saving.",13,Muted);p.Children.Add(message);
 var name=Field(p,"Product name","");var serving=Field(p,"One serving (copy exactly from the label)","");var fields=new TextBox[4];for(int i=0;i<4;i++)fields[i]=Field(p,Store.MacroNames[i]+" per serving","");var category=Choose(p,"Category",Store.Categories,"Snack");var container=Field(p,"Servings per container (optional)","");var extra=Field(p,"Fiber, sugar and sodium (optional notes)","");var confirm=new CheckBox{Content="I checked the serving basis and all four values against the label"};p.Children.Add(confirm);
 Action parse=delegate{var values=LabelReader.Parse(text.Text);for(int i=0;i<4;i++)fields[i].Text=values[i];var servingMatch=Regex.Match(text.Text,@"Serving size\s*:?\s*([^\r\n]+)",RegexOptions.IgnoreCase);if(servingMatch.Success)serving.Text=servingMatch.Groups[1].Value;var containerMatch=Regex.Match(text.Text,@"(?:about\s+)?(\d+(?:\.\d+)?)\s+servings? per container",RegexOptions.IgnoreCase);if(containerMatch.Success)container.Text=containerMatch.Groups[1].Value;var extraMatches=Regex.Matches(text.Text,@"(?:Dietary Fiber|Total Sugars|Sodium)\s*:?\s*\d+(?:\.\d+)?\s*(?:mg|g)",RegexOptions.IgnoreCase);extra.Text=string.Join("; ",System.Linq.Enumerable.Select(System.Linq.Enumerable.Cast<Match>(extraMatches),m=>m.Value));message.Text="Blank values were missing or ambiguous. Check calories are kcal and all values are for ONE serving.";};
 Func<string,Task> read=async delegate(string path){try{message.Text="Reading label on this computer…";var bitmap=new BitmapImage();bitmap.BeginInit();bitmap.CacheOption=BitmapCacheOption.OnLoad;bitmap.UriSource=new Uri(path);bitmap.EndInit();preview.Source=bitmap;text.Text=await Task.Run(()=>LabelReader.Read(path));parse();}catch(Exception e){message.Text=e.Message;}};
 var row=Row();var camera=Button("Access camera",async delegate{string path=CameraCapture.Take(w);if(path!=null)await read(path);},true);camera.Name="AccessCamera";row.Children.Add(camera);row.Children.Add(Button("Choose image",async delegate{var d=new OpenFileDialog{Filter="Label image|*.png;*.jpg;*.jpeg;*.bmp"};if(d.ShowDialog(w)==true)await read(d.FileName);}));row.Children.Add(Button("Paste image",async delegate{if(!Clipboard.ContainsImage())throw new ArgumentException("Copy a label image first.");string path=Path.Combine(Path.GetTempPath(),"MacroTracker-label-"+Guid.NewGuid().ToString("N")+".png");var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(Clipboard.GetImage()));using(var stream=File.Create(path))encoder.Save(stream);await read(path);}));row.Children.Add(Button("Extract from text",parse));p.Children.Insert(0,row);
 p.Children.Add(Button("Save reviewed food to favorites",delegate{if(confirm.IsChecked!=true)throw new ArgumentException("Review and confirm the label values first.");var v=new double[4];for(int i=0;i<4;i++)v[i]=Number(fields[i],false);Store.Validate(v,false);if(string.IsNullOrWhiteSpace(name.Text)||name.Text.Length>200||string.IsNullOrWhiteSpace(serving.Text))throw new ArgumentException("Enter the product name and serving size.");if(container.Text!="")Number(container,true);var r=new Dictionary<string,string>{{"name",name.Text},{"serving",serving.Text},{"category",(string)category.SelectedItem},{"notes","Reviewed nutrition label. Servings/container: "+container.Text+". "+extra.Text},{"quantity","1"}};for(int i=0;i<4;i++)r[Store.MacroNames[i].ToLowerInvariant()]=v[i].ToString(CultureInfo.InvariantCulture);store.Favorite(r);w.Close();Navigate("Library");Notice("Label saved to favorites");},true));w.ShowDialog();}
}
}
