using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Web.Script.Serialization;
namespace MacroTracker {
public sealed partial class MainWindow {
 Window Form(string title,out StackPanel panel){var w=new Window{Title=title,Owner=this,Width=720,Height=700,MinWidth=550,MinHeight=450,Background=Bg,Foreground=Ink,Resources=Resources,WindowStartupLocation=WindowStartupLocation.CenterOwner};panel=new StackPanel{Margin=new Thickness(22)};w.SourceInitialized+=delegate{RoundWindow(w);};w.Content=new ScrollViewer{Background=Bg,Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};return w;}
 ComboBox Choose(StackPanel p,string title,IEnumerable<string> options,string current){p.Children.Add(Label(title,13,Muted));var c=new ComboBox{ItemsSource=options.ToArray(),SelectedItem=current,Padding=new Thickness(8),Margin=new Thickness(0,0,0,12)};p.Children.Add(c);return c;}
 void OpenLibraryTab(string tab){libraryStartTab=tab;Navigate("Library");}
 void Library(){
 Heading("Food library","Save meals, recipes, snacks and drinks. Copies remain independently editable.");
 var actions=Row();actions.Children.Add(Button("Create meal / recipe",delegate{LibraryEditor(null);},true));actions.Children.Add(Button("Save foods from a day",SelectDiaryMeal));actions.Children.Add(Button("Scan nutrition label",ScanLabel));content.Children.Add(actions);
 var search=Field(content,"Search library or history","");
 var tabOptions=new[]{"Recents","History","Favorites","Saved Meals","Recipes","Snacks","Drinks"};var firstTab=tabOptions.Contains(libraryStartTab)?libraryStartTab:"History";libraryStartTab=null;var tabs=Choose(content,"Browse",tabOptions,firstTab);
 var listing=new StackPanel();content.Children.Add(listing);
 Action render=delegate{
 listing.Children.Clear();string tab=(string)tabs.SelectedItem;string query=search.Text;
 if(tab=="Recents"||tab=="History"||tab=="Favorites"){
 var entries=tab=="Recents"?store.Recent().Where(r=>r["name"].IndexOf(query,StringComparison.OrdinalIgnoreCase)>=0).ToList():store.Db.Query(tab=="History"?"SELECT * FROM foods WHERE name LIKE ? ORDER BY day DESC,time DESC LIMIT 100":"SELECT * FROM favorites WHERE name LIKE ? ORDER BY name LIMIT 100","%"+query+"%");
 foreach(var r in entries){var item=r;var p=new StackPanel();p.Children.Add(Label(item["name"]+" · "+Store.F(Store.Values(item)[0])+" kcal",18,Ink));p.Children.Add(Label((item.ContainsKey("day")?item["day"]+" · ":"")+item["category"]+" · "+Store.F(FoodPortion.Quantity(item))+" × "+item["serving"],12,Muted));var row=Row();row.Children.Add(Button("Copy to day",delegate{CopyFood(item);}));row.Children.Add(Button("Save as meal / recipe",delegate{LibraryEditor(new List<LibraryItem>{LibraryItem.From(item)});}));row.Children.Add(Button(tab=="Favorites"?"Remove favorite":"Favorite",delegate{if(tab=="Favorites")store.Db.Query("DELETE FROM favorites WHERE id=?",item["id"]);else store.Favorite(item);Navigate("Library");}));p.Children.Add(row);listing.Children.Add(Box(p));}
 if(entries.Count==0)listing.Children.Add(Label("No matching entries yet.",15,Muted));
 }else{
 string kind=tab=="Saved Meals"?"Meal":tab=="Recipes"?"Recipe":tab=="Snacks"?"Snack":"Drink";
 var records=store.Db.Query("SELECT * FROM library WHERE kind=? AND name LIKE ? ORDER BY name",kind,"%"+query+"%");
 foreach(var r in records){var record=r;var p=new StackPanel();p.Children.Add(Label(r["name"],20,Ink));var items=new JavaScriptSerializer().Deserialize<List<LibraryItem>>(r["items"]);p.Children.Add(Label(items.Count+" ingredients · "+r["yield"]+" servings · "+Store.F(items.Sum(x=>x.Macros[0])/Store.Num(r["yield"]))+" kcal/serving",13,Muted));var buttons=Row();buttons.Children.Add(Button("Add to diary",delegate{LogSaved(record);},true));buttons.Children.Add(Button("Edit recipe",delegate{LibraryEditor(null,record);}));buttons.Children.Add(Button("Delete",delegate{if(MessageBox.Show(this,"Delete this saved item? Logged copies are kept.","Library",MessageBoxButton.YesNo)==MessageBoxResult.Yes){store.Db.Query("DELETE FROM library WHERE id=?",record["id"]);Navigate("Library");}}));p.Children.Add(buttons);listing.Children.Add(Box(p));}
 if(records.Count==0)listing.Children.Add(Label("Create your first saved "+kind.ToLowerInvariant()+" above.",15,Muted));
 }};
 search.TextChanged+=delegate{render();};tabs.SelectionChanged+=delegate{render();};render();
 }
 void CopyFood(Dictionary<string,string> food){StackPanel p;var w=Form("Copy food",out p);var date=new SoftDatePicker(w,selected);p.Children.Add(date);var time=Field(p,"Time eaten",DateTime.Now.ToString("HH:mm"));var qty=Field(p,"Quantity",Store.F(FoodPortion.Quantity(food)));var category=Choose(p,"Meal category",Store.Categories,food["category"]);p.Children.Add(Button("Add copy",delegate{if(!date.SelectedDate.HasValue)throw new ArgumentException("Choose a date.");double q=ReadQuantity(qty);store.SaveFood(null,date.SelectedDate.Value,food["name"],Store.Values(food).Select(v=>v*q/FoodPortion.Quantity(food)).ToArray(),(string)category.SelectedItem,food["serving"],food["notes"],time.Text,q);w.Close();Navigate(page);Notice("Food copied");},true));w.ShowDialog();}
 void LibraryEditor(List<LibraryItem> initial,Dictionary<string,string> existing=null){
 StackPanel p;var w=Form("Build a meal or recipe",out p);var items=existing==null?(initial??new List<LibraryItem>()):new JavaScriptSerializer().Deserialize<List<LibraryItem>>(existing["items"]);
 var name=Field(p,"Name",existing==null?"":existing["name"]);var kind=Choose(p,"Type",new[]{"Meal","Recipe","Snack","Drink"},existing==null?"Meal":existing["kind"]);var servings=Field(p,"Servings made by the complete batch",existing==null?"1":existing["yield"]);var grams=Field(p,"Finished batch weight in grams (optional; 0 = unused)",existing==null?"0":existing["grams"]);
 var list=new StackPanel();p.Children.Add(list);Action refresh=null;refresh=delegate{list.Children.Clear();foreach(var i in items.ToList()){var item=i;var line=Row();line.Children.Add(Label(Store.F(item.Quantity)+" × "+item.Name+" · "+Store.F(item.Macros[0])+" kcal",14,Ink));line.Children.Add(Button("Remove",delegate{items.Remove(item);refresh();}));list.Children.Add(line);}};refresh();
 p.Children.Add(Button("New ingredient / USDA search",delegate{IngredientEditor(delegate(LibraryItem item){items.Add(item);refresh();});}));
 var search=Field(p,"Search favorites and food history","");p.Children.Add(Label("Saved ingredient results",12,Muted));var results=new ListBox{Height=130,DisplayMemberPath="Value",Name="IngredientResults",Background=Bg,Foreground=Ink,BorderThickness=new Thickness(0),Padding=new Thickness(3)};var itemStyle=new Style(typeof(ListBoxItem));itemStyle.Setters.Add(new Setter(Control.ForegroundProperty,Ink));itemStyle.Setters.Add(new Setter(Control.BackgroundProperty,Brush("#00000000")));itemStyle.Setters.Add(new Setter(Control.PaddingProperty,new Thickness(10,7,10,7)));itemStyle.Setters.Add(new Setter(FrameworkElement.MarginProperty,new Thickness(0,1,0,1)));itemStyle.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty,HorizontalAlignment.Stretch));var selectedItem=new Trigger{Property=ListBoxItem.IsSelectedProperty,Value=true};selectedItem.Setters.Add(new Setter(Control.BackgroundProperty,Green));selectedItem.Setters.Add(new Setter(Control.ForegroundProperty,Bg));itemStyle.Triggers.Add(selectedItem);results.ItemContainerStyle=itemStyle;p.Children.Add(new Border{Background=Bg,BorderBrush=Line,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Padding=new Thickness(3),Margin=new Thickness(0,0,0,12),Child=results});var source=store.Db.Query("SELECT * FROM favorites ORDER BY name").Concat(store.Db.Query("SELECT id,name,calories,protein,carbs,fat,category,serving,notes,quantity FROM foods ORDER BY id DESC")).GroupBy(r=>(r["name"].Trim()+"\n"+r["serving"].Trim()).ToLowerInvariant()).Select(g=>g.First()).OrderBy(r=>r["name"]).ToList();
 Action find=delegate{results.ItemsSource=source.Where(r=>r["name"].IndexOf(search.Text.Trim(),StringComparison.OrdinalIgnoreCase)>=0).Take(50).Select(r=>new KeyValuePair<Dictionary<string,string>,string>(r,r["name"]+(string.IsNullOrWhiteSpace(r["serving"])?"":"  ·  "+r["serving"])+"  ·  "+Store.F(Store.Values(r)[0])+" kcal")).ToList();};search.TextChanged+=delegate{find();};find();
 var amount=Field(p,"Ingredient quantity (replaces the source quantity)","1");p.Children.Add(Button("Add selected ingredient",delegate{if(results.SelectedItem==null)throw new ArgumentException("Select an ingredient.");var r=((KeyValuePair<Dictionary<string,string>,string>)results.SelectedItem).Key;var item=LibraryItem.From(r);double q=ReadQuantity(amount);item.Macros=item.Macros.Select(x=>x*q/item.Quantity).ToArray();item.Quantity=q;items.Add(item);refresh();}));
 p.Children.Add(Label("Select one saved result, set its quantity, and add it. Use New ingredient for USDA lookup or manual entry.",12,Muted));
 p.Children.Add(Button("Save to library",delegate{store.SaveLibrary(existing==null?null:existing["id"],name.Text,(string)kind.SelectedItem,items,ReadQuantity(servings),Number(grams,false));w.Close();Navigate("Library");},true));w.ShowDialog();
 }
 void LogSaved(Dictionary<string,string> record){StackPanel p;var w=Form("Add "+record["name"],out p);var date=new SoftDatePicker(w,selected);p.Children.Add(date);var time=Field(p,"Time eaten",DateTime.Now.ToString("HH:mm"));var amount=Field(p,"Amount","1");var unit=Choose(p,"Unit",new[]{"Servings","Grams"},"Servings");var category=Choose(p,"Log under",Store.Categories,record["kind"]=="Drink"?"Drink":record["kind"]=="Snack"?"Snack":"Lunch");p.Children.Add(Button("Add all ingredients",delegate{if(!date.SelectedDate.HasValue)throw new ArgumentException("Choose a date.");store.LogLibrary(record,date.SelectedDate.Value,ReadQuantity(amount),(string)unit.SelectedItem=="Grams",time.Text,(string)category.SelectedItem);w.Close();Navigate(page);Notice("Saved meal added");},true));w.ShowDialog();}
 void DayTargets(){Heading("Day targets","Create training, rest or custom presets. The week runs Sunday through Saturday.");var p=new StackPanel();var names=store.Db.Query("SELECT name FROM presets ORDER BY name").Select(r=>r["name"]).ToList();var preset=Choose(p,"Load a preset",names,null);var name=Field(p,"Preset name","Training Day");var fields=new TextBox[4];var defaults=store.Defaults();for(int i=0;i<4;i++)fields[i]=Field(p,Store.MacroNames[i],Store.F(defaults[i]));preset.SelectionChanged+=delegate{if(preset.SelectedItem==null)return;var r=store.Db.Query("SELECT * FROM presets WHERE name=?",preset.SelectedItem)[0];name.Text=r["name"];for(int i=0;i<4;i++)fields[i].Text=Store.F(Store.Values(r)[i]);};
 p.Children.Add(Button("Save preset",delegate{var v=fields.Select(f=>Number(f,true)).ToArray();Store.Validate(v,true);if(string.IsNullOrWhiteSpace(name.Text))throw new ArgumentException("Name the preset.");store.Db.Query("INSERT OR REPLACE INTO presets VALUES(?,?,?,?,?)",name.Text.Trim(),v[0],v[1],v[2],v[3]);Navigate("Day Targets");},true));content.Children.Add(Box(p));
 var schedulePanel=new StackPanel();schedulePanel.Children.Add(Label("Weekly schedule",22,Ink));var picks=new ComboBox[7];var options=new[]{"Default"}.Concat(names).ToArray();for(int i=0;i<7;i++){var row=store.Db.Query("SELECT preset FROM schedule WHERE weekday=?",i);picks[i]=Choose(schedulePanel,((DayOfWeek)i).ToString(),options,row.Count==0?"Default":row[0]["preset"]);}
 schedulePanel.Children.Add(Button("Save schedule",delegate{store.Db.Transaction(delegate{for(int i=0;i<7;i++){if((string)picks[i].SelectedItem=="Default")store.Db.Query("DELETE FROM schedule WHERE weekday=?",i);else store.Db.Query("INSERT OR REPLACE INTO schedule VALUES(?,?)",i,picks[i].SelectedItem);}});Notice("Schedule saved for days without saved targets");}));schedulePanel.Children.Add(Label("Existing days retain their saved targets. Apply an explicit override below to change today or another day.",12,Muted));content.Children.Add(Box(schedulePanel));
 var over=new StackPanel();var date=new SoftDatePicker(this,selected);over.Children.Add(date);var choice=Choose(over,"One-day override",options,"Default");over.Children.Add(Button("Apply to selected day",delegate{if(!date.SelectedDate.HasValue)throw new ArgumentException("Choose a date.");var r=store.Db.Query("SELECT * FROM presets WHERE name=?",choice.SelectedItem);store.SetDayTargets(date.SelectedDate.Value,r.Count==0?store.Defaults():Store.Values(r[0]));store.Set("daytype:"+Store.Day(date.SelectedDate.Value),(string)choice.SelectedItem);Notice("Selected day's targets updated");}));content.Children.Add(Box(over));}
 void CheckIn(){Heading("Weekly check-in","Review completed days, reflect, and plan your next week.");DateControls();DateTime start=Store.Sunday(selected).AddDays(-7),end=start.AddDays(6);content.Children.Add(Label(start.ToString("MMM d")+" – "+end.ToString("MMM d, yyyy"),22,Ink));WeeklyChart(start);var p=new StackPanel();var complete=Enumerable.Range(0,7).Select(i=>start.AddDays(i)).Where(d=>store.Complete(d)).ToList();if(complete.Count>0){p.Children.Add(Label("Average macros · P "+Store.F(complete.Average(d=>store.Totals(d)[1]))+"g · C "+Store.F(complete.Average(d=>store.Totals(d)[2]))+"g · F "+Store.F(complete.Average(d=>store.Totals(d)[3]))+"g",16,Green));foreach(var group in complete.GroupBy(d=>store.Get("daytype:"+Store.Day(d),"Default")))p.Children.Add(Label(group.Key+" · "+group.Count()+" completed days · "+Store.F(group.Average(d=>store.Totals(d)[0]))+" kcal/day",13,Muted));}var rows=store.Db.Query("SELECT * FROM checkins WHERE week=?",Store.Day(start));var saved=rows.FirstOrDefault();var hunger=Choose(p,"Hunger",new[]{"Not recorded","Low","Moderate","High"},saved==null?"Not recorded":saved["hunger"]);var energy=Choose(p,"Energy",new[]{"Not recorded","Low","Moderate","High"},saved==null?"Not recorded":saved["energy"]);var training=Choose(p,"Workout performance",new[]{"Not recorded","Rest week","Below usual","As usual","Above usual"},saved==null?"Not recorded":saved["training"]);var note=Field(p,"Reflection",saved==null?"":saved["note"]);var focus=Field(p,"One focus for next week",saved==null?"":saved["focus"]);
 var weights=store.Db.Query("SELECT * FROM weights WHERE day>=? AND day<=?",Store.Day(start.AddDays(-7)),Store.Day(end));var current=weights.Where(r=>string.CompareOrdinal(r["day"],Store.Day(start))>=0).ToList();var previous=weights.Where(r=>string.CompareOrdinal(r["day"],Store.Day(start))<0).ToList();double factor=store.Get("unit","lb")=="lb"?2.2046226218:1; p.Children.Add(Label(current.Count>0?"Average weight: "+Store.F(current.Average(r=>Store.Num(r["kg"]))*factor)+" "+store.Get("unit","lb")+(previous.Count>0?" · Change: "+Store.F((current.Average(r=>Store.Num(r["kg"]))-previous.Average(r=>Store.Num(r["kg"])))*factor):" · No previous-week comparison"):"No weigh-ins for this week.",16,Green));
 if(weights.Count>=2){var graph=new System.Windows.Controls.Canvas{Height=100};var ordered=weights.OrderBy(x=>x["day"]).ToList();graph.SizeChanged+=delegate{graph.Children.Clear();double min=ordered.Min(x=>Store.Num(x["kg"])),span=Math.Max(.5,ordered.Max(x=>Store.Num(x["kg"]))-min);var line=new System.Windows.Shapes.Polyline{Stroke=Green,StrokeThickness=3};DateTime first=DateTime.Parse(ordered[0]["day"]),last=DateTime.Parse(ordered[ordered.Count-1]["day"]);foreach(var r in ordered)line.Points.Add(new Point(10+(graph.ActualWidth-25)*(DateTime.Parse(r["day"])-first).TotalDays/Math.Max(1,(last-first).TotalDays),85-70*(Store.Num(r["kg"])-min)/span));graph.Children.Add(line);};p.Children.Add(Label("Weight trend · previous and reviewed week",13,Muted));p.Children.Add(graph);}
 p.Children.Add(Button("Save check-in · keep targets",delegate{store.Db.Query("INSERT OR REPLACE INTO checkins VALUES(?,?,?,?,?,?)",Store.Day(start),hunger.SelectedItem,energy.SelectedItem,training.SelectedItem,note.Text,focus.Text);Notice("Weekly check-in saved");},true));p.Children.Add(Button("Edit next week's schedule",delegate{Navigate("Day Targets");}));content.Children.Add(Box(p));}
}
}
