using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Threading;
using Microsoft.Win32;
using Forms=System.Windows.Forms;

namespace MacroTracker {
public sealed partial class MainWindow : Window {
    readonly Store store; StackPanel content; StackPanel navigation; ScrollViewer scroll; TextBlock status,brandTitle,brandSubtitle; DateTime selected=DateTime.Today, lastDay=DateTime.Today; string page="Dashboard"; Forms.NotifyIcon tray; DispatcherTimer timer; bool exiting; bool test; string lastReminder; Window foodDialog;
    public static Brush Bg=Brush("#10151E"), Card=Brush("#1B2432"), Muted=Brush("#9CAFC5"), Ink=Brush("#F3F6FC"), Green=Brush("#9CE4BD");
    public static Brush StatusUnder=Brush("#F2C94C"),StatusNear=Brush("#35D07F"),StatusOver=Brush("#FF665E"),StatusFuture=Brush("#56636B");
    static string[] Colors={"#9CE4BD","#B4AAFF","#83CCF3","#F4C78C"};
    public static Brush Brush(string hex) {return new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex));}
    public MainWindow(Store data,bool smoke) {
        store=data; ApplyTheme(); test=smoke; Title="Macro Tracker"; Width=1180; Height=820; MinWidth=940; MinHeight=640; Background=Bg; Foreground=Ink; FontFamily=new FontFamily("Segoe UI"); FontSize=14; WindowStartupLocation=WindowStartupLocation.CenterScreen;
        InstallStyles();SourceInitialized+=delegate{RoundWindow(this);};
        var shell=new Grid{Background=Bg,Margin=new Thickness(12)};shell.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});shell.RowDefinitions.Add(new RowDefinition());Content=shell;
        var header=new DockPanel{LastChildFill=true,Margin=new Thickness(18,8,12,8)};sidebarSurface=new Border{Background=Card,CornerRadius=new CornerRadius(26),Child=header,Margin=new Thickness(0,0,0,10)};shell.Children.Add(sidebarSurface);
        var brand=new StackPanel{Width=185,Margin=new Thickness(4,0,12,0),VerticalAlignment=VerticalAlignment.Center};brandTitle=Label("◒  MACRO",24,Ink);brandSubtitle=Label("A LITTLE BETTER, DAILY",9,Muted);brand.Children.Add(brandTitle);brand.Children.Add(brandSubtitle);DockPanel.SetDock(brand,Dock.Left);header.Children.Add(brand);
        navigation=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};header.Children.Add(navigation);
        foreach(string name in new[]{"Dashboard","Food Log","Library","Day Targets","Check-In","History","Weight","Settings"}) {string n=name;var b=Button(name,delegate{selected=DateTime.Today;Navigate(n);});b.FontSize=13;b.Margin=new Thickness(0,0,4,0);b.Padding=new Thickness(9,8,9,8);navigation.Children.Add(b);}
        var area=new DockPanel{Margin=new Thickness(18,8,12,8),Background=Bg};Grid.SetRow(area,1);shell.Children.Add(area);
        status=Label("Ready · All changes saved locally",12,Muted); status.Margin=new Thickness(0,12,0,0); DockPanel.SetDock(status,Dock.Bottom); area.Children.Add(status);InstallUpdateBar(area);
        scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled}; area.Children.Add(scroll); content=new StackPanel{Margin=new Thickness(0,0,12,0)}; scroll.Content=content;
        store.EnsureDay(DateTime.Today); SetupTray();
        timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(15)}; timer.Tick+=delegate {Safe(Tick);}; timer.Start();
        Closing+=delegate(object sender,System.ComponentModel.CancelEventArgs e) {if(!exiting && !test && store.Get("setup","")=="1" && store.Get("tray","1")=="1") {e.Cancel=true; Hide();} else {timer.Stop(); tray.Dispose();}};
        KeyDown+=delegate(object sender,System.Windows.Input.KeyEventArgs e) {if(e.Key==System.Windows.Input.Key.N && System.Windows.Input.Keyboard.Modifiers==System.Windows.Input.ModifierKeys.Control) {AddFood(null,false); e.Handled=true;}};
        Navigate(store.Get("setup","")=="1"?"Dashboard":"Welcome");
    }
    void InstallStyles() {
        var b=new Style(typeof(Button)); b.Setters.Add(new Setter(Control.ForegroundProperty,Ink)); b.Setters.Add(new Setter(Control.BackgroundProperty,Card)); b.Setters.Add(new Setter(Control.BorderThicknessProperty,new Thickness(0))); b.Setters.Add(new Setter(Control.PaddingProperty,new Thickness(15,10,15,10))); b.Setters.Add(new Setter(FrameworkElement.MarginProperty,new Thickness(0,0,8,0))); b.Setters.Add(new Setter(Control.CursorProperty,System.Windows.Input.Cursors.Hand));
        var template=new ControlTemplate(typeof(Button)); var border=new FrameworkElementFactory(typeof(Border)); border.SetValue(Border.CornerRadiusProperty,new CornerRadius(18)); border.SetBinding(Border.BackgroundProperty,new System.Windows.Data.Binding("Background"){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)}); var presenter=new FrameworkElementFactory(typeof(ContentPresenter)); presenter.SetValue(FrameworkElement.MarginProperty,new Thickness(14,10,14,10)); presenter.SetBinding(ContentPresenter.HorizontalAlignmentProperty,new System.Windows.Data.Binding("HorizontalContentAlignment"){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)}); border.AppendChild(presenter); template.VisualTree=border; b.Setters.Add(new Setter(Control.TemplateProperty,template)); var hover=new Trigger{Property=UIElement.IsMouseOverProperty,Value=true}; hover.Setters.Add(new Setter(UIElement.OpacityProperty,0.78)); b.Triggers.Add(hover); var focus=new Trigger{Property=UIElement.IsKeyboardFocusedProperty,Value=true}; focus.Setters.Add(new Setter(Control.BackgroundProperty,Green)); b.Triggers.Add(focus); Resources.Add(typeof(Button),b);
        var t=new Style(typeof(TextBox)); t.Setters.Add(new Setter(Control.BackgroundProperty,Bg)); t.Setters.Add(new Setter(Control.ForegroundProperty,Ink)); t.Setters.Add(new Setter(Control.BorderBrushProperty,Brush("#41516A"))); t.Setters.Add(new Setter(Control.PaddingProperty,new Thickness(10))); t.Setters.Add(new Setter(Control.FontSizeProperty,15.0)); t.Setters.Add(new Setter(TextBox.CaretBrushProperty,Ink)); Resources.Add(typeof(TextBox),t);
        var c=new Style(typeof(CheckBox)); c.Setters.Add(new Setter(Control.ForegroundProperty,Ink)); c.Setters.Add(new Setter(FrameworkElement.MarginProperty,new Thickness(0,10,0,10))); Resources.Add(typeof(CheckBox),c);InstallSoftStyles();
    }
    public static TextBlock Label(string text,double size,Brush color) {return new TextBlock{Text=text,FontSize=size,Foreground=color,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,7)};}
    Button Button(string text,Action action,bool primary=false) {var b=new Button{Content=text,HorizontalContentAlignment=HorizontalAlignment.Center}; if(primary){b.Background=Green;b.Foreground=Bg;} b.Click+=delegate{Safe(action);}; return b;}
    static StackPanel Row() {return new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,8,0,8)};}
    static Border Box(UIElement child) {return new Border{Background=Card,BorderBrush=Brush(Ink.ToString()=="#FF14223B"?"#DCE4EF":"#35404B"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(26),Padding=new Thickness(22),Margin=new Thickness(0,0,0,16),Child=child};}
    void AddSettingsElement(UIElement child,string tag="SettingsElement") {var host=new Grid{MaxWidth=1100,HorizontalAlignment=HorizontalAlignment.Stretch,Tag=tag};host.Children.Add(child);content.Children.Add(host);}
    void AddSettingsBox(UIElement child) {AddSettingsElement(Box(child),"SettingsSection");}
    void SettingsHeading(string title,string subtitle) {var panel=new StackPanel();panel.Children.Add(Label(title,32,Ink));panel.Children.Add(Label(subtitle,14,Muted));panel.Children.Add(new Border{Height=16});AddSettingsElement(panel,"SettingsHeading");}
    Button SettingsAction(string text,Action action,double width=210) {var button=Button(text,action,true);button.Width=width;button.HorizontalAlignment=HorizontalAlignment.Left;return button;}
    void Safe(Action action) {try{action();}catch(Exception e){if(test)throw;MessageBox.Show(this,e.Message,"Macro Tracker",MessageBoxButton.OK,MessageBoxImage.Warning); status.Text="Couldn't complete that change. Please try again.";}}
    void Notice(string text) {status.Text=text+" · Saved locally";}
    void Heading(string title,string subtitle) {content.Children.Add(Label(title,32,Ink)); content.Children.Add(Label(subtitle,14,Muted)); content.Children.Add(new Border{Height=16});}
    public void Navigate(string name) {page=name;content.Children.Clear();scroll.ScrollToTop();foreach(var button in navigation.Children.OfType<Button>()){button.Background=(string)button.Content==name?Green:Card;button.Foreground=(string)button.Content==name?Bg:Ink;}if(name=="Welcome"){Settings(true);return;}if(name=="Dashboard")ModernDashboard();if(name=="Library")Library();if(name=="Day Targets")DayTargets();if(name=="Check-In")CheckIn();if(name=="Food Log")FoodLog();if(name=="History")History();if(name=="Weight")Weight();if(name=="Settings")Settings(false);}
    void DateControls() {var row=Row(); row.Children.Add(Button("‹ Previous",delegate{selected=selected.AddDays(-1);Navigate(page);})); var date=new SoftDatePicker(this,selected){Width=205,Margin=new Thickness(0,0,8,0)}; date.SelectedDateChanged+=delegate{if(date.SelectedDate.HasValue){selected=date.SelectedDate.Value;Navigate(page);}}; row.Children.Add(date); row.Children.Add(Button("Next ›",delegate{selected=selected.AddDays(1);Navigate(page);})); row.Children.Add(Button("Today",delegate{selected=DateTime.Today;Navigate(page);})); content.Children.Add(row);}
    void Dashboard() {
        Heading("Make today count.",DateTime.Today.ToString("dddd, MMMM d, yyyy")+"  ·  Your daily nutrition at a glance");
        var actions=Row(); actions.Children.Add(Button("+  Add food",delegate{selected=DateTime.Today;AddFood(null,false);},true)); actions.Children.Add(Label("Ctrl + N for quick add",12,Muted)); content.Children.Add(actions);
        MacroCards(DateTime.Today); var totals=store.Totals(DateTime.Today); var target=store.Targets(DateTime.Today);
        var note=new StackPanel(); note.Children.Add(Label("CONSISTENCY OVER PERFECTION",11,Green)); note.Children.Add(Label(totals[1]>=target[1]?"Protein target reached. Nice work.":Store.F(Math.Max(0,target[1]-totals[1]))+"g of protein to go today.",23,Ink)); note.Children.Add(Label("Log meals, snacks, and drinks as you go. Every entry counts.",13,Muted)); content.Children.Add(Box(note));
        content.Children.Add(Label("Today's food",21,Ink)); EntryList(DateTime.Today,5); QuickFoods();
    }
    void MacroCards(DateTime date) {var grid=new System.Windows.Controls.Primitives.UniformGrid{Columns=4,Margin=new Thickness(0,12,0,8)}; var total=store.Totals(date);var target=store.Targets(date);for(int i=0;i<4;i++){var p=new StackPanel();p.Children.Add(Label(Store.MacroNames[i].ToUpperInvariant(),11,Brush(Colors[i])));p.Children.Add(Label(Store.F(total[i])+(i==0?"":"g"),30,Ink));p.Children.Add(Label("of "+Store.F(target[i])+(i==0?" kcal":"g"),12,Muted));p.Children.Add(new ProgressBar{Minimum=0,Maximum=target[i],Value=Math.Min(total[i],target[i]),Height=7,Foreground=Brush(Colors[i]),Background=Brush("#344052"),BorderThickness=new Thickness(0),Margin=new Thickness(0,0,0,13)});p.Children.Add(Label(Store.F(Math.Abs(target[i]-total[i]))+(i==0?" calories":"g")+(total[i]>target[i]?" over target":" remaining"),13,Muted));var box=Box(p);box.Margin=new Thickness(0,0,12,12);grid.Children.Add(box);}content.Children.Add(grid);}
    void FoodLog() {Heading("Food log",selected==DateTime.Today?"Today · Keep the small things in the picture.":selected.ToString("D"));DateControls();var actions=Row();actions.Children.Add(Button("+  Add food",delegate{AddFood(null,false);},true));content.Children.Add(actions);MacroCards(selected);EntryList(selected,0);QuickFoods();}
    void EntryList(DateTime date,int limit) {
        var entries=store.Foods(date); if(entries.Count==0){var p=new StackPanel();p.Children.Add(Label("A fresh page for your day",19,Ink));p.Children.Add(Label("No entries yet. Add a meal, snack, or drink to start tracking.",14,Muted));content.Children.Add(Box(p));return;}
        foreach(var entry in limit>0?entries.Take(limit):entries) {var e=entry;var layout=new DockPanel();var buttons=Row();buttons.Children.Add(Button("☆",delegate{store.Favorite(e);Notice("Added to favorites");}));buttons.Children.Add(Button("Edit",delegate{AddFood(e,true);}));buttons.Children.Add(Button("Delete",delegate{if(MessageBox.Show(this,"Delete “"+e["name"]+"”?","Delete entry",MessageBoxButton.YesNo,MessageBoxImage.Question)==MessageBoxResult.Yes){store.Db.Query("DELETE FROM foods WHERE id=?",e["id"]);Navigate(page);Notice("Entry deleted");}}));DockPanel.SetDock(buttons,Dock.Right);layout.Children.Add(buttons);var p=new StackPanel();p.Children.Add(Label(e["name"],18,Ink));p.Children.Add(Label(e["category"]+"  ·  "+e["time"].Substring(0,5)+("  ·  "+FoodPortion.Description(e)),12,Muted));p.Children.Add(Label(Store.F(Store.Num(e["calories"]))+" kcal   /   P "+e["protein"]+"g   /   C "+e["carbs"]+"g   /   F "+e["fat"]+"g",13,Green));if(e["notes"]!="")p.Children.Add(Label(e["notes"],12,Muted));layout.Children.Add(p);content.Children.Add(Box(layout));}
    }
    void QuickFoods() {content.Children.Add(Label("Your usuals",21,Ink));var favorites=store.Db.Query("SELECT * FROM favorites ORDER BY name");content.Children.Add(Label("FAVORITES",11,Muted));var f=Row(); foreach(var e in favorites){var item=e;var group=Row();group.Children.Add(Button("★ "+e["name"],delegate{AddFood(item,false);}));group.Children.Add(Button("×",delegate{store.Db.Query("DELETE FROM favorites WHERE id=?",item["id"]);Navigate(page);}));f.Children.Add(group);} var wrap=new WrapPanel();foreach(var child in f.Children.Cast<UIElement>().ToArray()){f.Children.Remove(child);wrap.Children.Add(child);}content.Children.Add(wrap);if(favorites.Count==0)content.Children.Add(Label("Use ☆ on a logged food to save a favorite.",13,Muted));content.Children.Add(Label("RECENT FOODS",11,Muted));var recent=new WrapPanel();foreach(var e in store.Recent()){var item=e;var b=Button(e["name"],delegate{AddFood(item,false);});b.Margin=new Thickness(0,0,8,8);recent.Children.Add(b);}content.Children.Add(recent);}
    TextBox Field(StackPanel panel,string label,string value) {panel.Children.Add(Label(label,12,Muted));var box=new TextBox{Text=value,Margin=new Thickness(0,0,0,14),MaxLength=2000};panel.Children.Add(box);return box;}
    double Number(TextBox box,bool positive) {double value;if(!double.TryParse(box.Text,NumberStyles.Float,CultureInfo.CurrentCulture,out value)||double.IsNaN(value)||double.IsInfinity(value)||value<(positive?0.1:0)||value>100000)throw new ArgumentException("Enter a valid "+(positive?"positive":"nonnegative")+" number (maximum 100,000).");return value;}
    static string DefaultCategory() {int h=DateTime.Now.Hour;return h<11?"Breakfast":h<14?"Lunch":h<17?"Snack":"Dinner";}
    void History() {
        Heading("Consistency, one day at a time.","Review your daily totals and the targets saved with each day."); DateControls();DateTime start=Store.Sunday(selected);DateTime end=start.AddDays(6);var days=store.Db.Query("SELECT d.*,coalesce(sum(f.calories),0) tc,coalesce(sum(f.protein),0) tp,coalesce(sum(f.carbs),0) tcarbs,coalesce(sum(f.fat),0) tf,count(f.id) count FROM days d LEFT JOIN foods f ON f.day=d.day WHERE d.day>=? AND d.day<=? GROUP BY d.day ORDER BY d.day DESC",Store.Day(start),Store.Day(end));
        var tracked=days.Where(r=>Store.Num(r["count"])>0).ToList();var summary=new StackPanel();summary.Children.Add(Label(start.ToString("MMM d")+" – "+end.ToString("MMM d, yyyy"),21,Ink));summary.Children.Add(Label(tracked.Count+" logged days · averages use days with food entries",12,Muted));if(tracked.Count>0){summary.Children.Add(Label(Store.F(tracked.Average(r=>Store.Num(r["tc"])))+" kcal   ·   "+Store.F(tracked.Average(r=>Store.Num(r["tp"])))+"g protein",25,Green));summary.Children.Add(Label("Average carbs "+Store.F(tracked.Average(r=>Store.Num(r["tcarbs"])))+"g   ·   Average fat "+Store.F(tracked.Average(r=>Store.Num(r["tf"])))+"g",14,Muted));summary.Children.Add(Label(tracked.Count(r=>Store.Num(r["tc"])<=Store.Num(r["calories"]))+" / "+tracked.Count+" days within calories   ·   "+tracked.Count(r=>Store.Num(r["tp"])>=Store.Num(r["protein"]))+" / "+tracked.Count+" protein goals reached",14,Ink));}else summary.Children.Add(Label("No food logged this week yet.",16,Ink));content.Children.Add(Box(summary));
        content.Children.Add(Label("Daily history",21,Ink));var all=store.Db.Query("SELECT d.*,coalesce(sum(f.calories),0) tc,coalesce(sum(f.protein),0) tp,coalesce(sum(f.carbs),0) tcarbs,coalesce(sum(f.fat),0) tf,count(f.id) count FROM days d LEFT JOIN foods f ON f.day=d.day GROUP BY d.day ORDER BY d.day DESC");foreach(var d in all){var day=d;var p=new StackPanel();p.Children.Add(Label(DateTime.Parse(d["day"],CultureInfo.InvariantCulture).ToString("ddd, MMM d, yyyy"),18,Ink));p.Children.Add(Label(d["tc"]+" kcal  ·  P "+d["tp"]+"g  ·  C "+d["tcarbs"]+"g  ·  F "+d["tf"]+"g",14,Green));p.Children.Add(Label(d["count"]=="0"?"No food logged":(Store.Num(d["tc"])<=Store.Num(d["calories"])?"Within calorie target":"Over calorie target")+"  ·  "+(Store.Num(d["tp"])>=Store.Num(d["protein"])?"Protein target reached":"Below protein target"),12,Muted));p.Children.Add(Button("View day →",delegate{selected=DateTime.Parse(day["day"],CultureInfo.InvariantCulture);Navigate("Food Log");}));content.Children.Add(Box(p));}
    }
    void Weight() {
        string unit=store.Get("unit","lb"); double factor=unit=="lb"?2.2046226218:1;
        Heading("The bigger picture","Optional morning weigh-ins · Look at the trend, not a single day.");var r=store.Db.Query("SELECT * FROM weights ORDER BY day DESC");var p=new StackPanel(); if(r.Count>0){var week=r.Where(x=>string.CompareOrdinal(x["day"],Store.Day(DateTime.Today.AddDays(-6)))>=0 && string.CompareOrdinal(x["day"],Store.Day(DateTime.Today))<=0).ToList();p.Children.Add(Label("LATEST     "+Store.F(Store.Num(r[0]["kg"])*factor)+" "+unit,30,Green));p.Children.Add(Label("Recorded "+r[0]["day"]+(r.Count>1?"   ·   Previous "+Store.F(Store.Num(r[1]["kg"])*factor)+" "+unit:""),13,Muted));p.Children.Add(Label(week.Count>0?"7-day average: "+Store.F(week.Average(x=>Store.Num(x["kg"]))*factor)+" "+unit+"  ("+week.Count+" weigh-ins)":"No weigh-ins in the last 7 days",16,Ink));}else p.Children.Add(Label("Add your first weigh-in when you're ready.",20,Ink));
        var date=new SoftDatePicker(this,DateTime.Today){Width=205,HorizontalAlignment=HorizontalAlignment.Left};p.Children.Add(date);var value=Field(p,"Morning weight ("+unit+")","");value.Width=180;value.HorizontalAlignment=HorizontalAlignment.Left;p.Children.Add(Button("Save weigh-in",delegate{double w=Number(value,true);if(w/factor<10||w/factor>700)throw new ArgumentException("Weight must be between 10 and 700 kg (22–1,543 lb).");if(!date.SelectedDate.HasValue||date.SelectedDate.Value>DateTime.Today)throw new ArgumentException("Choose today or an earlier date.");store.Db.Query("INSERT OR REPLACE INTO weights(day,kg) VALUES(?,?)",Store.Day(date.SelectedDate.Value),w/factor);Navigate("Weight");Notice("Weight saved");},true));content.Children.Add(Box(p));
        if(r.Count>=2){content.Children.Add(Label("Weight trend · last 30 weigh-ins",19,Ink));var data=r.Take(30).Reverse().ToList();var canvas=new Canvas{Height=190,ClipToBounds=true};var border=Box(canvas);content.Children.Add(border);canvas.SizeChanged+=delegate{canvas.Children.Clear();double min=data.Min(x=>Store.Num(x["kg"])),max=data.Max(x=>Store.Num(x["kg"]));double span=Math.Max(0.5,max-min);DateTime first=DateTime.Parse(data[0]["day"]),last=DateTime.Parse(data[data.Count-1]["day"]);var line=new Polyline{Stroke=Green,StrokeThickness=3};for(int i=0;i<data.Count;i++){double x=20+(canvas.ActualWidth-45)*(DateTime.Parse(data[i]["day"])-first).TotalDays/Math.Max(1,(last-first).TotalDays);double y=145-110*(Store.Num(data[i]["kg"])-min)/span;line.Points.Add(new Point(x,y));}canvas.Children.Add(line);var low=Label(Store.F(min*factor)+" – "+Store.F(max*factor)+" "+unit+"   |   "+first.ToString("MMM d")+" → "+last.ToString("MMM d"),12,Muted);Canvas.SetTop(low,162);canvas.Children.Add(low);};}
        foreach(var entry in r){var e=entry;var row=Row();row.Children.Add(Label(e["day"]+"     "+Store.F(Store.Num(e["kg"])*factor)+" "+unit,16,Ink));row.Children.Add(Button("Edit",delegate{date.SelectedDate=DateTime.Parse(e["day"]);value.Text=Store.F(Store.Num(e["kg"])*factor);value.Focus();}));row.Children.Add(Button("Delete",delegate{if(MessageBox.Show(this,"Delete this weigh-in?","Weight",MessageBoxButton.YesNo)==MessageBoxResult.Yes){store.Db.Query("DELETE FROM weights WHERE day=?",e["day"]);Navigate("Weight");}}));content.Children.Add(row);}
    }
    void Settings(bool welcome) {
        SettingsHeading(welcome?"Welcome to Macro Tracker":"Make it yours",welcome?"Set your daily targets and reminders. You're ready in a minute.":"Daily targets, gentle reminders, and your local data.");
        ThemeCard();UpdateSettingsCard();UsdaSettingsCard();
        var p=new StackPanel();p.Children.Add(Label("Daily targets",21,Ink));var targets=store.Defaults();var inputs=new TextBox[4];var grid=new System.Windows.Controls.Primitives.UniformGrid{Columns=2,MaxWidth=780,HorizontalAlignment=HorizontalAlignment.Left};for(int i=0;i<4;i++){var cell=new StackPanel{Margin=new Thickness(0,0,16,0),Width=380};inputs[i]=Field(cell,Store.MacroNames[i]+(i==0?" (kcal)":" (g)"),Store.F(targets[i]));grid.Children.Add(cell);}p.Children.Add(grid);var today=new CheckBox{Content="Apply these targets to today too",IsChecked=true};p.Children.Add(today);p.Children.Add(Label("Past days keep their saved targets. Calories are tracked independently from macros, including drinks.",12,Muted));p.Children.Add(SettingsAction(welcome?"Save targets & start tracking":"Save targets",delegate{store.SaveTargets(inputs.Select(x=>Number(x,true)).ToArray(),today.IsChecked==true);store.Set("setup","1");Navigate(welcome?"Dashboard":"Settings");Notice("Daily targets saved");},welcome?250:170));AddSettingsBox(p);
        ReminderSettings();
        if(welcome)return;
        var options=new StackPanel();options.Children.Add(Label("Desktop preferences",21,Ink));var trayCheck=new CheckBox{Content="Close to system tray (reminders keep running)",IsChecked=store.Get("tray","1")=="1"};options.Children.Add(trayCheck);trayCheck.Click+=delegate{Safe(delegate{store.Set("tray",trayCheck.IsChecked==true?"1":"0");Notice("Tray preference saved");});};var startup=new CheckBox{Content="Launch Macro Tracker when Windows starts",IsChecked=StartupEnabled()};options.Children.Add(startup);startup.Click+=delegate{Safe(delegate{using(var key=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run")){if(startup.IsChecked==true)key.SetValue("MacroTracker","\""+System.Reflection.Assembly.GetExecutingAssembly().Location+"\" --tray");else key.DeleteValue("MacroTracker",false);}Notice("Windows startup preference saved");});startup.IsChecked=StartupEnabled();};var units=new ComboBox{ItemsSource=new[]{"lb","kg"},SelectedItem=store.Get("unit","lb"),Width=110,HorizontalAlignment=HorizontalAlignment.Left,Padding=new Thickness(8)};options.Children.Add(Label("Weight display unit",12,Muted));options.Children.Add(units);units.SelectionChanged+=delegate{Safe(delegate{store.Set("unit",(string)units.SelectedItem);Notice("Weight unit saved");});};AddSettingsBox(options);
        var backup=new StackPanel();backup.Children.Add(Label("Your data stays here",21,Ink));var path=Label(store.Path,12,Muted);path.MaxWidth=780;path.HorizontalAlignment=HorizontalAlignment.Left;backup.Children.Add(path);var exportRow=Row();exportRow.Children.Add(Button("Export food CSV",delegate{Export(false);},true));exportRow.Children.Add(Button("Export weight CSV",delegate{Export(true);},true));backup.Children.Add(exportRow);var br=Row();br.Children.Add(Button("Back up database",delegate{var dialog=new SaveFileDialog{Filter="Macro Tracker backup|*.db",FileName="MacroTracker-"+Store.Day(DateTime.Today)+".db"};if(dialog.ShowDialog(this)==true){store.Backup(dialog.FileName);Notice("Database backed up");}},true));br.Children.Add(Button("Restore backup",delegate{var dialog=new OpenFileDialog{Filter="Macro Tracker backup|*.db;*.bak"};if(dialog.ShowDialog(this)==true && MessageBox.Show(this,"Replace your current data with this backup? A safety copy of your current database will be saved first.","Restore backup",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes){store.Restore(dialog.FileName);store.EnsureDay(DateTime.Today);Navigate("Settings");Notice("Backup restored");}},true));backup.Children.Add(br);AddSettingsBox(backup);AddSettingsElement(SettingsAction("Exit Macro Tracker",Exit,190));
    }
    bool StartupEnabled() {using(var key=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run"))return key!=null&&key.GetValue("MacroTracker")!=null;}
    void Export(bool weight) {var dialog=new SaveFileDialog{Filter="CSV file|*.csv",FileName=weight?"weight-history.csv":"food-history.csv"};if(dialog.ShowDialog(this)==true){store.Export(dialog.FileName,weight,store.Get("unit","lb"));Notice("History exported");}}
    void SetupTray() {
        tray=new Forms.NotifyIcon{Text="Macro Tracker",Icon=System.Drawing.Icon.ExtractAssociatedIcon(System.Reflection.Assembly.GetExecutingAssembly().Location),Visible=!test};var menu=new Forms.ContextMenuStrip();menu.Items.Add("Open Macro Tracker",null,delegate{Safe(delegate{Open();Navigate("Dashboard");});});menu.Items.Add("Quick Add Food",null,delegate{Safe(delegate{Open();selected=DateTime.Today;AddFood(null,false);});});menu.Items.Add("Today's Progress",null,delegate{Safe(delegate{var t=store.Totals(DateTime.Today);var goal=store.Targets(DateTime.Today);Notify("Today's progress",Store.F(t[0])+" / "+Store.F(goal[0])+" calories · "+Store.F(t[1])+" / "+Store.F(goal[1])+"g protein");});});menu.Items.Add("Snooze last reminder 15 min",null,delegate{Safe(delegate{if(lastReminder!=null){store.Snooze(lastReminder,DateTime.Now);Notify("Snoozed","We'll remind you again in 15 minutes.");}else Notify("No reminder to snooze","Use Settings to snooze a scheduled reminder.");});});menu.Items.Add(new Forms.ToolStripSeparator());menu.Items.Add("Exit",null,delegate{Exit();});tray.ContextMenuStrip=menu;tray.DoubleClick+=delegate{Open();};tray.BalloonTipClicked+=delegate{Safe(delegate{Open();selected=DateTime.Today;AddFood(null,false);});};
    }
    public void Open() {Show();WindowState=WindowState.Normal;Activate();}
    void Notify(string title,string message) {if(!test)tray.ShowBalloonTip(10000,title,message,Forms.ToolTipIcon.Info);}
    public void Tick() {var now=DateTime.Now;if(lastDay!=now.Date){lastDay=now.Date;store.EnsureDay(now);if(selected==now.Date.AddDays(-1))selected=now.Date;Navigate(page);}foreach(var r in store.Due(now)){lastReminder=r["id"];Notify("Time to log · Macro Tracker",store.Context(r["message"],now));store.Fired(r["id"],now);}}
    public void Exit() {exiting=true;Close();}
}
}
