using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Shapes;
namespace MacroTracker {
public sealed partial class MainWindow {
 void ApplyTheme(){string theme=store.Get("theme","Graphite");Bg=Brush(theme=="Purple"?"#191024":theme=="White / Red / Blue"?"#F3F6FC":"#10191D");Card=Brush(theme=="Purple"?"#291C38":theme=="White / Red / Blue"?"#FFFFFF":"#1A262C");Ink=Brush(theme=="White / Red / Blue"?"#14223B":"#F5F5FA");Muted=Brush(theme=="White / Red / Blue"?"#52637D":"#B6B6C9");Green=Brush(theme=="White / Red / Blue"?"#145AD6":theme=="Purple"?"#BF8AFF":"#38CFCD");Colors=new[]{"#38CFCD",theme=="White / Red / Blue"?"#145AD6":"#38CFCD",theme=="White / Red / Blue"?"#E23B38":theme=="Purple"?"#FF8D7D":"#F27B32",theme=="White / Red / Blue"?"#8B3FC4":"#B978F0"};StatusUnder=Brush(theme=="White / Red / Blue"?"#D99A00":"#F2C94C");StatusNear=Brush(theme=="White / Red / Blue"?"#16834A":"#35D07F");StatusOver=Brush(theme=="White / Red / Blue"?"#D7373F":"#FF665E");StatusFuture=Brush(theme=="White / Red / Blue"?"#AAB5C7":"#56636B");}
 void ThemeCard(){var p=new StackPanel();var theme=Choose(p,"Color theme",new[]{"Graphite","Purple","White / Red / Blue"},store.Get("theme","Graphite"));p.Children.Add(Button("Apply theme",delegate{store.Set("theme",(string)theme.SelectedItem);ApplyTheme();Background=Bg;Foreground=Ink;var shell=(Grid)Content;shell.Background=Bg;sidebarSurface.Background=Card;brandTitle.Foreground=Ink;brandSubtitle.Foreground=Muted;RoundWindow(this);foreach(var dock in shell.Children.OfType<DockPanel>())dock.Background=Bg;status.Foreground=Muted;Resources.Clear();InstallStyles();Navigate("Settings");Notice("Theme applied");},true));content.Children.Add(Box(p));}
 void ModernDashboard(){
  DashboardHeader();var actions=Row();actions.Children.Add(Button("Food library",delegate{Navigate("Library");}));actions.Children.Add(Button(store.Complete(selected)?"Reopen day":"Mark day complete",delegate{store.MarkComplete(selected,!store.Complete(selected));Navigate("Dashboard");}));content.Children.Add(actions);
  MacroOverview();WeeklyChart(Store.Sunday(selected));content.Children.Add(Button("Review last week",delegate{Navigate("Check-In");}));content.Children.Add(Label("Today's food",22,Ink));EntryList(selected,10);
 }
 void DashboardHeader(){var header=new Grid{Margin=new Thickness(0,0,0,6)};header.ColumnDefinitions.Add(new ColumnDefinition());header.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var greeting=new StackPanel();greeting.Children.Add(Label("Good "+(DateTime.Now.Hour<12?"morning":"afternoon"),32,Ink));greeting.Children.Add(Label(selected.ToString("dddd, MMMM d, yyyy")+" · "+store.Get("daytype:"+Store.Day(selected),"Default targets"),14,Muted));header.Children.Add(greeting);var controls=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,VerticalAlignment=VerticalAlignment.Center};controls.Children.Add(Button("‹ Previous",delegate{selected=selected.AddDays(-1);Navigate(page);}));var date=new SoftDatePicker(this,selected){Width=190,Margin=new Thickness(0,0,8,0)};date.SelectedDateChanged+=delegate{if(date.SelectedDate.HasValue){selected=date.SelectedDate.Value;Navigate(page);}};controls.Children.Add(date);controls.Children.Add(Button("Next ›",delegate{selected=selected.AddDays(1);Navigate(page);}));controls.Children.Add(Button("Today",delegate{selected=DateTime.Today;Navigate(page);}));controls.Children.Add(Button("+ Add food",delegate{AddFood(null,false);},true));Grid.SetColumn(controls,1);header.Children.Add(controls);content.Children.Add(header);}
 void MacroOverview(){var totals=store.Totals(selected);var goals=store.Targets(selected);var panel=new StackPanel();panel.Children.Add(Label("Today's macros",22,Ink));var layout=new Grid();layout.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(330)});layout.ColumnDefinitions.Add(new ColumnDefinition());
  var ringArea=new Grid{Width=275,Height=275,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};var canvas=new Canvas{Width=275,Height=275,Name="CombinedMacroRing"};ringArea.Children.Add(canvas);double radius=118;var track=new Ellipse{Width=radius*2,Height=radius*2,Stroke=StatusFuture,Opacity=.65,StrokeThickness=20};Canvas.SetLeft(track,137.5-radius);Canvas.SetTop(track,137.5-radius);canvas.Children.Add(track);double angle=-90;for(int i=1;i<=3;i++){double sweep=120*Math.Min(1,totals[i]/goals[i]);if(sweep>0)AddRingArc(canvas,137.5,radius,angle,sweep,Brush(Colors[i]));angle+=sweep;}
  var center=new StackPanel{Width=180,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};var calories=Label(Store.F(totals[0])+" kcal",27,Ink);calories.TextAlignment=TextAlignment.Center;var remaining=Label(Store.F(goals[0]-totals[0])+" remaining",14,Green);remaining.TextAlignment=TextAlignment.Center;center.Children.Add(calories);center.Children.Add(remaining);ringArea.Children.Add(center);layout.Children.Add(ringArea);
  var bars=new StackPanel{Margin=new Thickness(18,6,8,0),VerticalAlignment=VerticalAlignment.Center};for(int i=1;i<=3;i++){int macro=i;var item=new Grid{Margin=new Thickness(0,6,0,16)};item.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(145)});item.ColumnDefinitions.Add(new ColumnDefinition());var name=Label((i==1?"💪  ":i==2?"🌾  ":"🥑  ")+Store.MacroNames[i],19,Brush(Colors[i]));name.VerticalAlignment=VerticalAlignment.Center;item.Children.Add(name);var detail=new StackPanel();var percent=Math.Round(totals[i]/goals[i]*100);detail.Children.Add(Label(Store.F(totals[i])+" / "+Store.F(goals[i])+" g   ·   "+percent+"%",15,Ink));detail.Children.Add(new ProgressBar{Name="MacroBar"+macro,Minimum=0,Maximum=goals[i],Value=Math.Min(totals[i],goals[i]),Height=10,Foreground=Brush(Colors[i]),Background=StatusFuture,BorderThickness=new Thickness(0)});Grid.SetColumn(detail,1);item.Children.Add(detail);bars.Children.Add(item);}Grid.SetColumn(bars,1);layout.Children.Add(bars);panel.Children.Add(layout);content.Children.Add(Box(panel));
 }
 void AddRingArc(Canvas canvas,double center,double radius,double start,double sweep,Brush color){int steps=Math.Max(2,(int)Math.Ceiling(sweep/2));var line=new Polyline{Stroke=color,StrokeThickness=20,StrokeStartLineCap=PenLineCap.Flat,StrokeEndLineCap=PenLineCap.Flat,StrokeLineJoin=PenLineJoin.Round};for(int n=0;n<=steps;n++){double a=(start+sweep*n/steps)*Math.PI/180;line.Points.Add(new Point(center+radius*Math.Cos(a),center+radius*Math.Sin(a)));}canvas.Children.Add(line);}
 string CalorieStatus(DateTime date){if(!store.Complete(date)||store.Foods(date).Count==0)return "Incomplete";double delta=store.Totals(date)[0]-store.Targets(date)[0];return Math.Abs(delta)<=100?"Near":delta>100?"Over":"Under";}
 Brush CalorieStatusBrush(string status){return status=="Under"?StatusUnder:status=="Near"?StatusNear:status=="Over"?StatusOver:StatusFuture;}
 int LoggingStreak(){DateTime cursor=DateTime.Today;if(!store.Complete(cursor)||store.Foods(cursor).Count==0)cursor=cursor.AddDays(-1);int count=0;while(store.Complete(cursor)&&store.Foods(cursor).Count>0){count++;cursor=cursor.AddDays(-1);}return count;}
 FrameworkElement StatusLegend(Brush color,string text){var item=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,0,18,0)};item.Children.Add(new Ellipse{Width=11,Height=11,Fill=color,Margin=new Thickness(0,3,7,0)});item.Children.Add(Label(text,12,Muted));return item;}
 void WeeklyChart(DateTime start){var p=new StackPanel();p.Children.Add(Label("Calories this week · Sunday–Saturday",21,Ink));var canvas=new Canvas{Height=245,Name="WeeklyCalorieChart"};p.Children.Add(canvas);Action draw=delegate{canvas.Children.Clear();double width=Math.Max(400,canvas.ActualWidth),step=(width-60)/7;double max=Enumerable.Range(0,7).Max(i=>Math.Max(store.Totals(start.AddDays(i))[0],store.Targets(start.AddDays(i))[0]))*1.15;max=Math.Max(max,1);var goals=new Polyline{Stroke=Green,StrokeThickness=1.5,StrokeDashArray=new DoubleCollection(new double[]{3,4})};for(int i=0;i<7;i++){var date=start.AddDays(i);double value=store.Totals(date)[0],goal=store.Targets(date)[0];double x=35+i*step,h=value/max*175,y=195-goal/max*175;string state=CalorieStatus(date);var bar=new Rectangle{Width=Math.Max(12,step-22),Height=h,RadiusX=6,RadiusY=6,Fill=CalorieStatusBrush(state),Opacity=state=="Incomplete"?.58:1,Stroke=state=="Incomplete"?Green:null,StrokeThickness=state=="Incomplete"?2:0,Tag=state};Canvas.SetLeft(bar,x);Canvas.SetTop(bar,195-h);canvas.Children.Add(bar);var label=Label(date.ToString("ddd"),12,Muted);Canvas.SetLeft(label,x);Canvas.SetTop(label,205);canvas.Children.Add(label);var number=Label(value==0?"—":Store.F(value),11,Ink);Canvas.SetLeft(number,x);Canvas.SetTop(number,175-h);canvas.Children.Add(number);goals.Points.Add(new Point(x-5,y));goals.Points.Add(new Point(x+step-5,y));}canvas.Children.Add(goals);};canvas.SizeChanged+=delegate{draw();};
  var key=new Grid{Margin=new Thickness(0,2,0,7)};key.ColumnDefinitions.Add(new ColumnDefinition());key.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var streak=Label("🔥  "+LoggingStreak()+" day logging streak",15,Green);streak.Name="LoggingStreak";key.Children.Add(streak);var legend=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};legend.Children.Add(StatusLegend(StatusUnder,"Under goal"));legend.Children.Add(StatusLegend(StatusNear,"Within 100"));legend.Children.Add(StatusLegend(StatusOver,"Over goal"));Grid.SetColumn(legend,1);key.Children.Add(legend);p.Children.Add(key);p.Children.Add(Label("Colors apply after a day is marked complete · Accent outline + gray fill means incomplete · Dotted line is each day's target",12,Muted));
  var completed=Enumerable.Range(0,7).Select(i=>start.AddDays(i)).Where(d=>store.Complete(d)&&store.Foods(d).Count>0).ToList();if(completed.Count>0){var high=completed.OrderByDescending(d=>store.Totals(d)[0]).First();var low=completed.OrderBy(d=>store.Totals(d)[0]).First();p.Children.Add(Label("Average "+Store.F(completed.Average(d=>store.Totals(d)[0]))+" kcal · Highest "+Store.F(store.Totals(high)[0])+" ("+high.ToString("ddd")+") · Lowest "+Store.F(store.Totals(low)[0])+" ("+low.ToString("ddd")+")",14,Green));p.Children.Add(Label(completed.Count+" completed days · "+completed.Count(d=>Math.Abs(store.Totals(d)[0]-store.Targets(d)[0])<=100)+" within 100 calories · "+completed.Count(d=>store.Totals(d)[1]>=store.Targets(d)[1])+" protein targets reached",12,Muted));}else p.Children.Add(Label("Mark diary days complete to see accurate weekly statistics.",14,Muted));content.Children.Add(Box(p));}
}
}
