using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Shapes;
namespace MacroTracker {
public sealed partial class MainWindow {
 void ApplyTheme(){string theme=store.Get("theme","Graphite");Bg=Brush(theme=="Purple"?"#191024":theme=="White / Red / Blue"?"#F3F6FC":"#10191D");Card=Brush(theme=="Purple"?"#291C38":theme=="White / Red / Blue"?"#FFFFFF":"#1A262C");Ink=Brush(theme=="White / Red / Blue"?"#14223B":"#F5F5FA");Muted=Brush(theme=="White / Red / Blue"?"#52637D":"#B6B6C9");Green=Brush(theme=="White / Red / Blue"?"#145AD6":theme=="Purple"?"#BF8AFF":"#38CFCD");Colors=new[]{"#38CFCD",theme=="White / Red / Blue"?"#145AD6":"#38CFCD",theme=="White / Red / Blue"?"#E23B38":theme=="Purple"?"#FF8D7D":"#F27B32",theme=="White / Red / Blue"?"#8B3FC4":"#B978F0"};}
 void ThemeCard(){var p=new StackPanel();var theme=Choose(p,"Color theme",new[]{"Graphite","Purple","White / Red / Blue"},store.Get("theme","Graphite"));p.Children.Add(Button("Apply theme",delegate{store.Set("theme",(string)theme.SelectedItem);ApplyTheme();Background=Bg;Foreground=Ink;var shell=(Grid)Content;shell.Background=Bg;sidebarSurface.Background=Card;RoundWindow(this);foreach(var dock in shell.Children.OfType<DockPanel>())dock.Background=Grid.GetColumn(dock)==0?Card:Bg;foreach(var label in navigation.Children.OfType<TextBlock>())label.Foreground=Ink;status.Foreground=Muted;Resources.Clear();InstallStyles();Navigate("Settings");Notice("Theme applied");},true));content.Children.Add(Box(p));}
 void ModernDashboard(){Heading("Good "+(DateTime.Now.Hour<12?"morning":"afternoon"),selected.ToString("dddd, MMMM d, yyyy")+" · "+store.Get("daytype:"+Store.Day(selected),"Default targets"));DateControls();var row=Row();row.Children.Add(Button("+ Add food",delegate{AddFood(null,false);},true));row.Children.Add(Button("Food library",delegate{Navigate("Library");}));row.Children.Add(Button(store.Complete(selected)?"Reopen day":"Mark day complete",delegate{store.MarkComplete(selected,!store.Complete(selected));Navigate("Dashboard");}));content.Children.Add(row);
 var t=store.Totals(selected);var g=store.Targets(selected);var top=new Grid();top.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(290)});top.ColumnDefinitions.Add(new ColumnDefinition());var ringArea=new Grid{Width=260,Height=260,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};var canvas=new Canvas{Width=260,Height=260};ringArea.Children.Add(canvas);for(int i=1;i<=3;i++){double radius=119-(i-1)*19;var track=new Ellipse{Width=radius*2,Height=radius*2,Stroke=Muted,Opacity=.16,StrokeThickness=12};Canvas.SetLeft(track,130-radius);Canvas.SetTop(track,130-radius);canvas.Children.Add(track);double progress=Math.Min(1,t[i]/g[i]);if(progress>0){var line=new Polyline{Stroke=Brush(Colors[i]),StrokeThickness=12,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round};int steps=Math.Max(1,(int)(progress*180));for(int n=0;n<=steps;n++){double a=(-90+360*progress*n/steps)*Math.PI/180;line.Points.Add(new Point(130+radius*Math.Cos(a),130+radius*Math.Sin(a)));}canvas.Children.Add(line);}}
 var center=new StackPanel{Width=160,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};var calories=Label(Store.F(t[0])+" kcal",22,Ink);calories.TextAlignment=TextAlignment.Center;var remaining=Label(Store.F(g[0]-t[0])+" remaining",14,Green);remaining.TextAlignment=TextAlignment.Center;center.Children.Add(calories);center.Children.Add(remaining);ringArea.Children.Add(center);top.Children.Add(ringArea);var legend=new StackPanel{Margin=new Thickness(16)};Grid.SetColumn(legend,1);for(int i=1;i<=3;i++){legend.Children.Add(Label((i==1?"💪 ":i==2?"🌾 ":"🥑 ")+Store.MacroNames[i]+(i==1?" · outer":i==2?" · middle":" · inner"),20,Brush(Colors[i])));legend.Children.Add(Label(Store.F(t[i])+" / "+Store.F(g[i])+" g  ·  "+Math.Round(t[i]/g[i]*100)+"%",16,Ink));}top.Children.Add(legend);content.Children.Add(Box(top));WeeklyChart(Store.Sunday(selected));content.Children.Add(Button("Review last week",delegate{Navigate("Check-In");}));content.Children.Add(Label("Today's food",22,Ink));EntryList(selected,10);}
 void WeeklyChart(DateTime start){var p=new StackPanel();p.Children.Add(Label("Calories this week · Sunday–Saturday",21,Ink));var canvas=new Canvas{Height=245};p.Children.Add(canvas);Action draw=delegate{canvas.Children.Clear();double width=Math.Max(400,canvas.ActualWidth),step=(width-60)/7;double max=Enumerable.Range(0,7).Max(i=>Math.Max(store.Totals(start.AddDays(i))[0],store.Targets(start.AddDays(i))[0]))*1.15;max=Math.Max(max,1);var goals=new Polyline{Stroke=Green,StrokeThickness=1.5,StrokeDashArray=new DoubleCollection(new double[]{3,4})};for(int i=0;i<7;i++){var date=start.AddDays(i);double value=store.Totals(date)[0],goal=store.Targets(date)[0];double x=35+i*step,h=value/max*175,y=195-goal/max*175;var bar=new Rectangle{Width=Math.Max(12,step-22),Height=h,RadiusX=6,RadiusY=6,Fill=Brush(value>goal?Colors[2]:Colors[1]),Opacity=store.Complete(date)?1:.55};Canvas.SetLeft(bar,x);Canvas.SetTop(bar,195-h);canvas.Children.Add(bar);var label=Label(date.ToString("ddd"),12,Muted);Canvas.SetLeft(label,x);Canvas.SetTop(label,205);canvas.Children.Add(label);var number=Label(value==0?"—":Store.F(value),11,Ink);Canvas.SetLeft(number,x);Canvas.SetTop(number,175-h);canvas.Children.Add(number);goals.Points.Add(new Point(x-5,y));goals.Points.Add(new Point(x+step-5,y));}canvas.Children.Add(goals);};canvas.SizeChanged+=delegate{draw();};
 var completed=Enumerable.Range(0,7).Select(i=>start.AddDays(i)).Where(d=>store.Complete(d)).ToList();p.Children.Add(Label("Dotted line: each day's target · Faded bars: incomplete days",12,Muted));if(completed.Count>0){var high=completed.OrderByDescending(d=>store.Totals(d)[0]).First();var low=completed.OrderBy(d=>store.Totals(d)[0]).First();p.Children.Add(Label("Average "+Store.F(completed.Average(d=>store.Totals(d)[0]))+" kcal · Highest "+Store.F(store.Totals(high)[0])+" ("+high.ToString("ddd")+") · Lowest "+Store.F(store.Totals(low)[0])+" ("+low.ToString("ddd")+")",14,Green));p.Children.Add(Label(completed.Count+" completed days · "+completed.Count(d=>store.Totals(d)[0]<=store.Targets(d)[0])+" within calories · "+completed.Count(d=>store.Totals(d)[1]>=store.Targets(d)[1])+" protein targets reached",12,Muted));}else p.Children.Add(Label("Mark diary days complete to see accurate weekly statistics.",14,Muted));content.Children.Add(Box(p));}
}
}
